# Generated by Django 3.0 on 2022-01-15 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ref', models.CharField(max_length=500)),
                ('product_lible', models.CharField(max_length=500)),
                ('product_descrition', models.CharField(max_length=500)),
                ('product_created_at', models.DateTimeField(auto_now_add=True)),
                ('product_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_reference', models.CharField(blank=True, max_length=500, null=True)),
                ('product_lable', models.CharField(blank=True, max_length=500, null=True)),
                ('product_descreption', models.CharField(blank=True, max_length=500, null=True)),
                ('product_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('product_created_at', models.DateTimeField(auto_now_add=True)),
                ('product_updated_at', models.DateTimeField(auto_now=True)),
                ('product_ref_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_opdoo.BrandModel')),
            ],
        ),
        migrations.CreateModel(
            name='VendorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_reference', models.CharField(blank=True, max_length=500, null=True)),
                ('vendor_lable', models.CharField(blank=True, max_length=500, null=True)),
                ('vendor_descreption', models.CharField(blank=True, max_length=500, null=True)),
                ('vendor_phone', models.CharField(blank=True, max_length=500, null=True)),
                ('vendor_email', models.CharField(blank=True, max_length=500, null=True)),
                ('vendor_adress', models.CharField(blank=True, max_length=500, null=True)),
                ('product_created_at', models.DateTimeField(auto_now_add=True)),
                ('product_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVarianteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_variante_reference', models.CharField(blank=True, max_length=500, null=True)),
                ('product_variante_created_at', models.DateTimeField(auto_now_add=True)),
                ('product_variante_updated_at', models.DateTimeField(auto_now=True)),
                ('product_variante_ref_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_opdoo.ProductModel')),
                ('product_variante_ref_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_opdoo.VendorModel')),
            ],
        ),
    ]
