# Generated by Django 3.0 on 2022-01-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_opdoo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandmodel',
            old_name='product_created_at',
            new_name='brand_created_at',
        ),
        migrations.RenameField(
            model_name='brandmodel',
            old_name='product_descrition',
            new_name='brand_lable',
        ),
        migrations.RenameField(
            model_name='brandmodel',
            old_name='product_lible',
            new_name='brand_ref',
        ),
        migrations.RenameField(
            model_name='brandmodel',
            old_name='product_updated_at',
            new_name='brand_updated_at',
        ),
        migrations.RemoveField(
            model_name='brandmodel',
            name='product_ref',
        ),
    ]
