# Generated by Django 3.0 on 2022-01-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_opdoo', '0003_auto_20220115_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='product_quantity',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_buying_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
