# Generated by Django 3.0 on 2022-01-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_opdoo', '0005_productmodel_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_buying_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
