# Generated by Django 3.0 on 2022-01-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_opdoo', '0006_auto_20220115_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_buying_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_selling_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
