# Generated by Django 3.0 on 2022-01-17 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_opdoo', '0007_auto_20220115_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPOSModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_pos_user_key', models.CharField(blank=True, max_length=50, null=True)),
                ('session_pos_reciept_key', models.CharField(blank=True, max_length=50, null=True)),
                ('session_pos_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('session_pos_created_at', models.DateTimeField(auto_now_add=True)),
                ('session_pos_updated_at', models.DateTimeField(auto_now=True)),
                ('session_pos_ref_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_opdoo.ProductModel')),
            ],
        ),
    ]
