# Generated by Django 3.0 on 2022-01-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_opdoo', '0009_sessionposmodel_session_pos_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_birthday', models.DateField(blank=True, null=True)),
                ('customer_ville', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_cin', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_sexe', models.CharField(blank=True, choices=[(1, 'Masculin'), (2, 'Féminin')], max_length=10, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_profession', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_phone', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('customer_medical_mutual', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_authorization_mail', models.BooleanField(blank=True, default=False, null=True)),
                ('customer_authorization_sms', models.BooleanField(blank=True, default=False, null=True)),
                ('customer_created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_type',
            field=models.CharField(blank=True, choices=[(1, 'Monture'), (2, 'Verre'), (3, 'Produit'), (4, 'Service')], max_length=10, null=True),
        ),
    ]
