# Generated by Django 3.0 on 2022-02-07 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_opdoo', '0010_auto_20220122_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_history_od_SPH', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_od_CYL', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_od_AXE', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_od_ADD', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_od_IND', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_od_O', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_od_ECVL', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_od_EEVP', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_od_HT', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_od_ACC', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_od_BIN', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_og_SPH', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_og_CYL', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_og_AXE', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_og_ADD', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_og_IND', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_og_O', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_og_ECVL', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_og_EEVP', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_og_HT', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_og_ACC', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_og_BIN', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_provenance', models.CharField(blank=True, max_length=4, null=True)),
                ('customer_history_ordonnance', models.FileField(blank=True, null=True, upload_to='')),
                ('customer_history_ordonnance_date', models.DateField(blank=True, null=True)),
                ('customer_history_created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_history_updated_at', models.DateTimeField(auto_now=True)),
                ('customer_history_ref_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_opdoo.CustomerModel')),
            ],
        ),
    ]
