# Generated by Django 3.0 on 2022-02-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_opdoo', '0011_customerhistorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_od_ACC',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_od_ADD',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_od_AXE',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_od_BIN',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_od_CYL',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_od_ECVL',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_od_EEVP',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_od_HT',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_od_IND',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_od_O',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_od_SPH',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_og_ACC',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_og_ADD',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_og_AXE',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_og_BIN',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_og_CYL',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_og_ECVL',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_og_EEVP',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_og_HT',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_og_IND',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_og_O',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_og_SPH',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerhistorymodel',
            name='customer_history_provenance',
            field=models.CharField(blank=True, choices=[('OPHTALMOLOGUE', 'Ophtalmologue'), ('OPTICIEN', 'Opticien'), ('AU', 'Opticien')], max_length=20, null=True),
        ),
    ]
