# Generated by Django 3.0 on 2022-03-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_opdoo', '0012_auto_20220227_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerhistorymodel',
            name='customer_history_ordonnance_medecin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='customer_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
