# Generated by Django 3.0 on 2022-03-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_opdoo', '0013_auto_20220305_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_discount',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
