# Generated by Django 3.0 on 2022-04-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_opdoo', '0015_productmodel_product_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_monture_type',
            field=models.CharField(blank=True, choices=[(1, 'Optique'), (2, 'Solaire'), (3, 'Clip')], max_length=10, null=True),
        ),
    ]
