# Generated by Django 3.0 on 2022-04-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_opdoo', '0016_productmodel_product_monture_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantemodel',
            name='product_invoice_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
