# Generated by Django 3.0 on 2022-04-30 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_opdoo', '0017_productvariantemodel_product_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historique_payement_methode', models.CharField(blank=True, max_length=50, null=True)),
                ('historique_payement_total', models.CharField(blank=True, max_length=50, null=True)),
                ('historique_payement_session_key', models.CharField(blank=True, max_length=50, null=True)),
                ('historique_payement_carte_montant', models.FloatField(blank=True, null=True)),
                ('historique_payement_carte_numero_recu', models.CharField(blank=True, max_length=50, null=True)),
                ('historique_payement_cheque_montant', models.FloatField(blank=True, null=True)),
                ('historique_payement_cheque_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('historique_payement_espece_montant', models.FloatField(blank=True, null=True)),
                ('historique_payement_espece_remarque', models.CharField(blank=True, max_length=50, null=True)),
                ('historique_payement_created_at', models.DateTimeField(auto_now_add=True)),
                ('historique_payement_updated_at', models.DateTimeField(auto_now=True)),
                ('historique_payement_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_opdoo.CustomerModel')),
            ],
        ),
    ]
