# Generated by Django 3.0 on 2022-05-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_opdoo', '0018_paymenthistorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantemodel',
            name='product_excel_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
