# Generated by Django 3.0 on 2022-05-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_opdoo', '0019_productvariantemodel_product_excel_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariantemodel',
            old_name='product_excel_code',
            new_name='product_variante_excel_code',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_excel_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
