# Generated by Django 3.0 on 2022-05-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_opdoo', '0020_auto_20220508_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_declaration',
            field=models.CharField(blank=True, choices=[(1, 'C'), (2, 'NC')], max_length=10, null=True),
        ),
    ]
