# Generated by Django 3.0 on 2022-05-13 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_opdoo', '0021_productmodel_product_declaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_ref_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_opdoo.VendorModel'),
        ),
    ]
